### ISSUE TITLE
Heroku button app env issue.

### ISSUE THREAD

**Issue by reggi** [Polytonic/Sputnik#42]
> Configure environment
> There was an issue setting up your app environment.
> That add-on plan is only available to select users.

**Comment by Polytonic** [comment]
I haven't touched this in a while, but it looks like [Ruppell's Sockets](https://elements.heroku.com/addons/ruppells-sockets) is being discontinued by Heroku. The addon page loads properly, but it's not available when searching on [elements.heroku.com](https://elements.heroku.com/). I also get the following on new dyno creation:

>Something went wrong:
>The addon "ruppells-sockets" does not exist. Please ensure that the addon is spelled correctly.

If you need an immediate IRC bouncer, you're better off spinning up ZNC, especially considering the new limits on the Heroku free tier. That being said, I am looking to restart development on Sputnik (the bouncer, sans Heroku support), and I'll need testers. Feel free to respond if you're interested.
